name: Deploy To GCP App Engine

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy To GCP App Engine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GCP Auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: GCP Deploy
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        promote: false
